# Generated by Django 3.0.3 on 2020-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('isStudent', models.BooleanField(max_length=1)),
                ('date', models.DateField(auto_now=True)),
                ('dateTime', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('cv', models.FileField(upload_to='uploads/')),
                ('sallary', models.DecimalField(decimal_places=2, max_digits=4)),
                ('info', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='covers/')),
            ],
        ),
    ]
